services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      MONGO_DB_NAME: mongo
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      DJANGO_SECRET_KEY: mysecretkey
      DEBUG: "True"
    depends_on:
      - database
      - mongo

    networks:
      - app-network
    command: >
      bash -c "
      /usr/local/bin/wait-for-it.sh mongo:27017 &&
      /usr/local/bin/wait-for-it.sh mongo-express:8081 &&
      /usr/local/bin/wait-for-it.sh database:5432 &&
      /usr/local/bin/wait-for-it.sh adminer:8080 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  database:
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "5435:8080"
    depends_on:
      - database
    networks:
      - app-network
  
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  data:
  mongo_data:

networks:
  app-network:
    driver: bridge
