services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres

  